### ISSUE TITLE
Require VLR order

### ISSUE THREAD

**Issue by abellgithub** [copcio/copcio.github.io#11]
It would be nice if the "important" VLRs were all at the beginning of the file to reduce round-trips when first reading the data over a network connection. Suggest LASZIP VLR/COPC VLR/EB VLR.

**Comment by CCInc** [comment]
I agree, the COPC headers should be first in the file and the others such as wkt should come after.

**Comment by hobu** [comment]
> It would be nice if the "important" VLRs were all at the beginning of the file

We wouldn't require that they be the *first* VLR(s) or that any specific order of those VLRs would be necessary, correct?

**Comment by abellgithub** [comment]
No. That's exactly what it means.

**Comment by hobu** [comment]
Added in #16
