### ISSUE TITLE
Standardize fIle name structure

### ISSUE THREAD

**Issue by timodwhit** [copcio/copcio.github.io#17]
What do we think about standardizing the file name`[filename].copc.laz` to represent this file at a high level/easily?

We know there will be a VLR that defines the type as a COPC file, but that doesn't help some processors quickly know how to act (https://github.com/potree/potree/blob/develop/src/Potree.js#L139-L211)

It would be possible to build in the handling that does the check but as I understand it, it would require us to read the header for the VLR and then parse that (not ideal) to do the switch.

**Comment by hobu** [comment]
You will sometimes see a similar `[filename].cog.tif` naming convention in COG workflows, but I do not thing it is worthwhile to try to depend on this. 

The only way to know if a COPC file is one is to check for the VLRs, even if the user had a naming convention. This is why @abellgithub recommended and modified the COPC spec #11  put the COPC VLRs just after the header bytes so they can be grabbed in a single read of the same size all the time.

**Comment by hobu** [comment]
I don't think the specification needs to pronounce on this topic. If the community adopts the `[filename].copc.laz` working approach, that's great, but it isn't the specification's business to tell people what to do here.
