### ISSUE TITLE
span

### ISSUE THREAD

**Issue by connormanning** [copcio/copcio.github.io#26]
There's a chance here to correct the choice of EPT by not carrying over [`span`](https://entwine.io/entwine-point-tile.html#span) as the concept of resolution/density/spacing.

Entwine/EPT chose this term, which represents the grid width of the voxelization of the data nodes, because of its strict voxelized resolution guarantees at each node depth.  However this isn't the only sampling method possible, and Poisson, randomized, FIFO, and other non-gridded distributions may be possible.  Also, EPT had the specified limitation that it must be voxelized via a power of 2, which doesn't need to be true for COPC.

In general, `span` is a very confusing metric that needs a lot of explanation, even though what it represents is actually simple.  See for comparison the definition of the Potree equivalent to this field by @m-schuetz:
> spacing: (Number) Space between points at the root node. This value is halved at each octree level.

While this definition is directly convertible to a `span`, its meaning is much more concrete and easy to understand.

I would propose replacing the integral `span` field in the COPC header with a double-precision field representing the `spacing` or `distance` between points at the root node, to more clearly represent the density of the data at each depth without the indirection of `span`.

Possible terms include `spacing`, `distance`, `resolution`, and the description should indicate that this is not necessarily a 100% deterministic value: in a given node some points may end up being closer together or farther apart than this value depending on the sampling method.

**Comment by abellgithub** [comment]
@CCInc : I'm not sure what you're expecting, but there are no guarantees WRT absolute point spacing, so I'm not sure what you're trying to say.

**Comment by CCInc** [comment]
Are you talking about `Perhaps root_spacing to indicate it's only applicable at the root level?`? I was just going off the definition:

> spacing: (Number) Space between points at the root node. 

I was suggesting to make it clear within the variable name that it represents the approx spacing for the root node. Or am I misunderstanding?

**Comment by abellgithub** [comment]
Sorry. I wasn't clear.  I don't understand this comment:

> I am, however, concerned with the fact we can't rely on nodes voxelized to the power of two - will a field representing the the voxelization power be added?

**Comment by CCInc** [comment]
For example, in Connor's ept code for potree, a lot of the logic is dependent on `2` as the voxelization power to calculate the bounding box of each subnode. 

https://github.com/potree/potree/blob/e86cae71f2f8f615d7a2e5933e197fc8b8ae9a12/src/PointCloudEptGeometry.js#L140-L155

Given that COPC doesn't require a power of 2 for voxels, how can we calculate the bounding box of a given node? We'll need to know the voxelization power to calculate it, AFAIK.

With a power of 2, we can calculate the bounding box as half the parent bounding box in each dimension, but for a power of 3, the bounding box would be a third of the parent's bounding box. So my question was if we were going to add an entry to the COPC header that represents this power.

**Comment by abellgithub** [comment]
The span/point spacing has nothing to do with descending octree levels. An octree node, by definition, is always split into 8 subnodes for each level of refinement (divided in half for each of X, Y and Z). I don't think anyone has contemplated anything different.

I think the "voxel" terminology has been confusing and I hope that replacing `span` with a good definition for `spacing` will help alleviate this confusion.

**Comment by CCInc** [comment]
Got it, my bad.

**Comment by m-schuetz** [comment]
So for now, COPC uses an Octree? Seems fine for starters, Octrees work great. For future iterations I'm wondering if we should consider the possibility to extend COPC to AABB-based bounding-volume hierarchies? They might have the advantage that the boxes can fit much tighter to the underlying data; adjacent nodes could be merged if they have low occupancy; and for teapot-in-a-stadium scenarios, BVHs might allow indexers to advance by arbitrary and dynamic spacing-factors, e.g., a node for the "stadium" with spacing 1, having a child node for the "teapot" with spacing 0.001.

**Comment by abellgithub** [comment]
@CCInc : I think you're right, however, in that we don't have any notion of the root octree node location. I think my assumption was that the min/max X/Y/Z values would proivide this, but I don't think that can be counted on to give this, at least not precisely. Perhaps this is something that needs to be added.

**Comment by pierotofy** [comment]
I always found `span` to be a bit confusing, so all for renaming it. I personally like `resolution`, but other names work too.

**Comment by timodwhit** [comment]
Just closing the gap here: 

@hobu stated in #28 we need 
| definition of the cube with a centerpoint and a distance needs to go in the info VLR as well

Just to clarify: The cube here refers to the bounding box of the octree which is not necessarily the bounding box of the data, since the octree would be a perfect cube where the data might be more rectangular.  Is that correct?

Are the centerpoint and the distance commonly use and expensive operations?

**Comment by CCInc** [comment]
@timodwhit The cube may be different from the data extent because, technically, the octree grid doesn't have to start at the data minimum.

**Comment by CCInc** [comment]
@abellgithub I personally think min/max would be much easier and clearer to use, at least from a reader/writer implementation standpoint. Most end-users won't be dealing with the copc format anyways, just using an implementation. Were you thinking of storing as doubles or as `int32_t` and using the header scale/offset?

**Comment by hobu** [comment]
> I personally think min/max would be much easier and clearer to use

Our thought was it is possible to define min/max combinations that don't correspond to a cube, and what would it mean in that instance? A center point + distance is always a cube no matter what.

**Comment by CCInc** [comment]
Ah, you're right...

We could also do a min + distance as well, which is effectively the same as a center point... any reason to choose one over the other?

**Comment by hobu** [comment]
Added in #32
