### ISSUE TITLE
Update Structural Changes to Draft Specification

### ISSUE THREAD

**Issue by CCInc** [copcio/copcio.github.io#44]
I think this is outdated:

Add laz_vlr_offset, laz_vlr_size, wkt_vlr_offset, wkt_vlr_size, eb_vlr_offset, eb_vlr_size to the COPC VLR, replacing 6 reserved entries.

**Comment by abellgithub** [comment]
It shows a history. 4ddaa2f44a5dc06f2a4f1b484500b54cee96e92b perhaps makes these specific changes more clear.
