### ISSUE TITLE
Example Dataset

### ISSUE THREAD

**Issue by timodwhit** [copcio/copcio.github.io#5]
For EPT, it is pretty easy to understand the structure and the parsing, but this will be a little more verbose, should we add a sample dataset or a link to a sample dataset?

**Comment by hobu** [comment]
We plan to provide the new [Autzen classified](https://github.com/PDAL/data/blob/master/autzen/autzen-classified.laz) file as an example COPC. See https://github.com/PDAL/data/tree/master/autzen for details on the file

**Comment by abellgithub** [comment]
Of course, whether it's verbose or not depends on your code ;)

**Comment by timodwhit** [comment]
Perfect. Once that is live/spec finalized, we can close this out.

**Comment by abellgithub** [comment]
See 53ac80610eee496680afa0583844b3a483a2f827

It passes as a LAZ file. COPC-specific features not yet tested.
