### ISSUE TITLE
Sum error in implementation notes

### ISSUE THREAD

**Issue by Jean-Romain** [copcio/copcio.github.io#58]
In the implementation note you wrote

> COPC is designed so that a reader needs to know little about the structure of a LAZ file. **By reading the first 549 bytes (375 for the header + 54 for the COPC VLR header + 160 for the COPC VLR)**, the software can verify that the file is a COPC file and determine the point data record format and point data record length, both of which are necessary to create a LAZ decompressor.

375+54+160 = 589 not 549

**Comment by hobu** [comment]
Indeed. Thanks for the report. https://github.com/PDAL/PDAL/pull/3918
