### ISSUE TITLE
How to validate a COPC file?

### ISSUE THREAD

**Issue by omshinde** [copcio/copcio.github.io#63]
Hi! I'm working on converting `las` files to `copc.laz` format and have successfully generated the output files. However, I am looking for ways to validate the generated COPC files. 

I came across this link https://github.com/copcio/copcio.github.io?tab=readme-ov-file#validation..But the https://validate.copc.io/ option doesn't show any output and I am not sure how to use the cpp version.  So, is there any alternate ways to validate the COPC files? (maybe using Python API or pdal CLI similar to `pdal info`). 

Thanks.

**Comment by hobu** [comment]
If it is a small enough file, just drag and drop it onto https://validate.copc.io

**Comment by abellgithub** [comment]
https://github.com/hobuinc/copcverify (maybe that's what you meant by "cpp version") builds easily with cmake (no dependencies). You just say "copcverify [--dump --chunks] <filename>".

**Comment by omshinde** [comment]
> If it is a small enough file, just drag and drop it onto https://validate.copc.io

Thanks @hobu ..I tried that but after uploading the file the UI just vanished. I dig a bit deeper into the Network requests and found that the Cesium API is not getting authenticated

**Comment by omshinde** [comment]
> https://github.com/hobuinc/copcverify (maybe that's what you meant by "cpp version") builds easily with cmake (no dependencies). You just say "copcverify [--dump --chunks] <filename>".

Thanks @abellgithub I'll try this and get back. I might need to look into how to set this up for use in a Jupyter notebook though.

**Comment by hobu** [comment]
https://validate.copc.io works for me. If you post a link to your file we can provide some details.

As for Jupyter, laspy has COPC read support, so you might try that.

**Comment by omshinde** [comment]
Thanks! I'll try to provide a link for the file. 

Although, I setup the `copcverify` as suggested by @abellgithub and getting following output - 

```
(base) root@workspace8ilyebp6oygo74dk:~/copcverify# ./copcverify "maap-documentation-examples/copc/data/usa_neonsrer_2019_NEON_D14_SRER_DP1_L090-1_2019091314_unclassified_point_cloud_0000004.copc.laz"
terminate called after throwing an instance of 'lazperf::error'
  what():  Invalid LAS file. Incorrect magic number.
Aborted
```

Does that mean that the file is not correct?

**Comment by omshinde** [comment]
Originally, I was thinking if it would be a good utility to have a `pdal` validation for COPC similar to https://cogeotiff.github.io/rio-cogeo/Is_it_a_COG/#3-cog-validation is there for COGs. Maybe another filter imitating the same effect as `copcverify`. 

As most of the times the users are interested in just validating if the generated output is cloud-optimized or not. 

PS: @hobu I am able to get info for this file using `pdal info` as follows. We assumed that it is a valid COPC since it used `readers.copc` by default. Is that a valid assumption? Or could it anytime be possible that `pdal info` is showing the info but the file is not a valid COPC file?

**Comment by hobu** [comment]
If `pdal info` reports a `.copc` element, it is COPC data. 

You need to post a link to an example file for us to tell you any more.

**Comment by omshinde** [comment]
Here's the link to the file - https://drive.google.com/file/d/1mR7x4_vz8xrHf0wLmBZxP56Zbc1qPibH/view?usp=sharing

**Comment by hobu** [comment]
It has one point in it. Are you trying to mess with us? 😉

**Comment by omshinde** [comment]
Ahh extremely sorry @hobu .. I didn't realize yet there is only one point in this file. I'll check with another example and close this issue. Thanks for all your help.

**Comment by abellgithub** [comment]
I updated copcverify. It should no longer throw the exception you received.
