### ISSUE TITLE
questions on spec

### ISSUE THREAD

**Issue by rouault** [copcio/copcio.github.io#9]
- in CopcData, why int64_t span and not uint64_t ?
- in Entry, why int32_t byteSize and not uint32_t ?  And given that it might be size of the child hierarchy page, and that Page::count is 64 bit, shouldn't that be a 64 bit integer ?
- in Entry, why int32_t pointCount, and not uint32_t ?
- in Entry,  int32_t pointCount: why not have it a uint32_t and use 0 as a special value instead of -1 ?

**Comment by abellgithub** [comment]
I think this answers most of these questions:

https://github.com/copcio/copcio.github.io/pull/2#discussion_r687878486

To add:

-  `Page::count` is 64 bit in order to guarantee that all data is naturally aligned.
- `Entry::pointCount` uses -1 as a sentinel value to be consistent with EPT.

**Comment by rouault** [comment]
>     * is 64 bit in order to guarantee that all data is naturally aligned.

wouldn't a 32 bit count + 32 bit reserved/alignment fields be clearer ?

**Comment by abellgithub** [comment]
>>  is 64 bit in order to guarantee that all data is naturally aligned.
> wouldn't a 32 bit count + 32 bit reserved/alignment fields be clearer ?

That's an option. I don't think it much matters. There really is no reason to limit the page count, but I also can't imagine more than INT_MAX pages. But don't look to me for prognostication -- When they first came out and were the size and weight of a brick, I didn't think cell phones would take off.

**Comment by rouault** [comment]
> There really is no reason to limit the page count

if Page::count can be larger than 32 bits, then Entry::byteSize should be 64 bit.
Actually if Page::count is limited to 32 bits and byteSize is also 32 bits, then Page::count cannot be larger than INT_MAX / sizeof(Entry)

**Comment by abellgithub** [comment]
The number of pages, `Page::count`, is unrelated to the size of the data chunks (`Entry::byteSize`). Data chunks are limited to 2^32-1 by the LAZ file format.  Maybe I'm misunderstanding.

But you're right that the idea that `Page::count` might exceed INT_MAX is silly. I don't have any problem changing the type. I just wanted the data aligned for those who may take advantage of that.

**Comment by abellgithub** [comment]
Oh wait. I take this back. You're correct, as usual. I was forgetting that we store the size of the pages when the pointCount was -1, so I think your suggestion is a good one.

If you're traversing the data in the expected way, you don't need the page count at all since the size is in the parent. The only reason I stuck it in was in case someone wanted to read the hierarchy in one go without worrying about the pages. But perhaps in that case it's also not necessary because you can ignore the entries that point to child pages.

I'm happy to remove it altogether or change it to 32 bit.

**Comment by abellgithub** [comment]
I went ahead and removed the value to eliminate confusion: 1bd99ac63a3b30a276e17c1731a19c893ed3766e
